ocp_installation_path: /home/user/installation
pullsecret: '{"auths":{"cloud.openshift.com":{"a.....'
sshKey: "ssh-rsa AAAAB3....."
sshprivatekey: |
  -----BEGIN RSA PRIVATE KEY-----
......
-----END RSA PRIVATE KEY-----
cert_manager_issuer_mail: xxx@xxx.com

## VMWare Data
vsphere_hostname: xxxx.xxxx.redhat.com
vsphere_username: sandbox-xxxx@demo
vsphere_password: ""
vsphere_datacenter: XXXX-Datacenter
vsphere_cluster: Cluster-X
vsphere_datastore: workload_share_XXXX
vsphere_network: segment-sandbox-xxxxx
vsphere_folder: sandbox-xxxxx
ocp_base_domain: dynamic.xxxxxxxx.io
ocp_cluster_name: xxxxxxx
ocp_machine_network_cidr: 192.168.xx.0/24
ocp_vip_api: 192.168.xx.yy
ocp_vip_ingress: 192.168.xx.yy
ocp_worker_cpus: 16
ocp_worker_mem: 49152

## Azure Data
azure_cluster_name: cloud
azure_cluster_region: northeurope
azure_cloud_name: AzurePublicCloud
azure_resource_group: openenv-xxxxx
azure_base_domain: xxxxx.redhatworkshops.io
azure_client_id: xxxxxxxx-xxxxxxxxxx-xxxxxxxxx-xxxxx
azure_client_secret: xxxxxxxxxxxxxx
azure_tenant_id: xxxxxxxx.onmicrosoft.com
azure_subscription_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
azure_submariner_worker_size: Standard_D2s_v3

## What execute
install_vmware_cluster: true
odf: true
acm: true
install_azure_cluster: true
submariner: true
crosscluster: true
letsencrypt: true