ocp_installation_path: ""
ocp_version: ""
pullsecret: ""
sshKey: ""
sshprivatekey: |
  -----BEGIN 
  -----END RSA PRIVATE KEY-----

## VMWare Data
vsphere_hostname: 
vsphere_username: 
vsphere_password: 
vsphere_datacenter: 
vsphere_cluster: 
vsphere_datastore: 
vsphere_network: 
vsphere_folder: 
ocp_base_domain: 
ocp_cluster_name: 
ocp_vip_api: 
ocp_vip_ingress: 


## Azure Data
azure_cluster_name: 
azure_cluster_region: 
azure_cloud_name: 
azure_resource_group: 
azure_base_domain: 
azure_client_id: 
azure_client_secret: 
azure_tenant_id: 
azure_subscription_id: 


