---
kind: Secret
apiVersion: v1
metadata:
  name: cloud-init-frontend
stringData:
  userdata: |
    #cloud-config
    system_info:
      default_user:
        name: fedora
        plain_text_passwd: fedora
        lock_passwd: false
        sudo: ALL=(ALL) NOPASSWD:ALL
    package_update: false
    package_upgrade: false
    packages:
      - nano
    write_files:
      - path: /etc/containers/systemd/frontend.container
        content: |
          [Unit]
          Description=Frontend
          StartLimitIntervalSec=0
          [Container]
          Image=quay.io/mvalledi/stock-example-app-frontend:latest
          ContainerName=frontend
          PublishPort=8080:8080
          #Pull=Always
          EnvironmentFile=/var/env/podman.env
          [Service]
          Restart=always
          RestartSec=5s
          TimeoutStartSec=10
          ExecStartPre=/usr/bin/bash -c 'mkdir /var/env; mount /dev/vdc /var/env'
          [Install]
          WantedBy=multi-user.target default.target
    runcmd:
      - setenforce 0
      - sed -i 's/^SELINUX=.*/SELINUX=disabled/' /etc/selinux/config
      - systemctl daemon-reload
      - systemctl start frontend
      - systemctl enable --now frontend
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: frontend
    kubevirt.io/dynamic-credentials-support: 'true'
    vm.kubevirt.io/template: fedora-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.34.1
  name: frontend
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: frontend
      spec:
        source:
          pvc:
            name: fedora
            namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 6Gi
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: frontend
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            - disk:
                bus: virtio
              name: environment-disk
              serial: O9RLWI
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.6.0
        memory:
          guest: 2Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: frontend
          name: rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: cloud-init-frontend
        - configMap:
            name: stock-parameters
          name: environment-disk
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    kubevirt.io/domain: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: stock
spec:
  to:
    name: frontend
    weight: 100
    kind: Service
  host: ''
  path: ''
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    externalCertificate:
      name: showroom-tls-secret
  port:
    targetPort: 8080
  alternateBackends: []
