
- name: Kubevirt - Patch hyperconverge with cpu
  kubernetes.core.k8s:
    kubeconfig: "{{item}}"
    state: patched
    api_version: hco.kubevirt.io/v1beta1
    kind: HyperConverged
    name: kubevirt-hyperconverged
    namespace: openshift-cnv
    definition:
      spec:
        defaultCPUModel: Broadwell-v2
  loop: 
    - "/tmp/{{ azure_cluster_name }}-kubeconfig"
    - "{{ocp_installation_path}}/auth/kubeconfig"

- name: Kubevirt - Update KubeVirt UI ConfigMap feature gate
  kubernetes.core.k8s:
    kubeconfig: "{{ocp_installation_path}}/auth/kubeconfig"
    state: patched
    kind: ConfigMap
    name: kubevirt-ui-features
    namespace: openshift-cnv
    definition:
      data:
        kubevirtCrossClusterMigration: "true"
     

- name: Check Sources Imports 
  ansible.builtin.shell: |
    COUNT=$(oc --kubeconfig="{{ item }}" get vs -n "openshift-virtualization-os-images" --no-headers 2>/dev/null | wc -l)
    [[ $COUNT -lt 6 ]] && oc --kubeconfig="{{ item }}" delete dataimportcron --all -n "openshift-virtualization-os-images"   
  loop: 
    - "/tmp/{{ azure_cluster_name }}-kubeconfig"
    - "{{ocp_installation_path}}/auth/kubeconfig"    
  register: shell_result
  failed_when: shell_result.rc != 0 and shell_result.rc != 1    


- name: Kubevirt - Create custom role with missing permissions
  kubernetes.core.k8s:
    kubeconfig: "{{item}}"
    state: present
    template: "files/kubevirt-custom-role.yaml"
  loop: 
    - "/tmp/{{ azure_cluster_name }}-kubeconfig"
    - "{{ocp_installation_path}}/auth/kubeconfig"


- name: Kubevirt - DataVolume Fedora 
  kubernetes.core.k8s:
    kubeconfig: "{{ocp_installation_path}}/auth/kubeconfig"
    state: present
    template: "files/datavolume-fedora.yaml"

- name: Showroom - ClusterRole to allow openshift-route SA to have cert permissions (cert-manager)
  kubernetes.core.k8s:
    kubeconfig: "{{ocp_installation_path}}/auth/kubeconfig"
    state: present
    template: "files/certmanager-clusterole-lab.yaml"