- name: LetsEncrypt - Install cert-manager Operator
  kubernetes.core.k8s:
    kubeconfig: "{{kubeconfig}}"
    state: present
    template: "files/certmanager.yaml"


- name: LetsEncrypt -  Wait for the CRD Certificate to become available
  kubernetes.core.k8s_info:
    kubeconfig: "{{kubeconfig}}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: certificates.cert-manager.io
  register: r_crd_certificates
  retries: 200
  delay: 10
  until:
  - r_crd_certificates.resources is defined
  - r_crd_certificates.resources | list | length == 1

- name: LetsEncrypt -  Wait for the CRD ClusterIssue to become available
  kubernetes.core.k8s_info:
    kubeconfig: "{{kubeconfig}}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: clusterissuers.cert-manager.io
  register: r_crd_issuer
  retries: 200
  delay: 10
  until:
  - r_crd_issuer.resources is defined
  - r_crd_issuer.resources | list | length == 1

- name: LetsEncrypt - Create ClusterIssuer
  kubernetes.core.k8s:
    kubeconfig: "{{kubeconfig}}"
    state: present
    template: "files/certmanager-issuer.yaml"


- name: Wait for multiple certificates to be ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{kubeconfig}}"
    api_version: cert-manager.io/v1
    kind: ClusterIssuer
    name: letsencrypt-prod
    wait: yes
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300

- name: LetsEncrypt - Create Console and Oauth certificates
  kubernetes.core.k8s:
    kubeconfig: "{{kubeconfig}}"
    state: present
    template: "files/certmanager-console-certificates.yaml"


- name: Wait for multiple certificates to be ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{kubeconfig}}"
    api_version: cert-manager.io/v1
    kind: Certificate
    name: "{{ item.name }}"
    namespace: "{{ item.namespace }}"
    wait: yes
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300
  loop:
    - { name: "custom-console-cert", namespace: "openshift-ingress" }
    - { name: "oauth-cert", namespace: "openshift-config" }
    - { name: "custom-console-cert", namespace: "openshift-console" }
    - { name: "oauth-cert", namespace: "openshift-authentication" }

  
- name: Patch resource console and oauth 
  kubernetes.core.k8s:
    kubeconfig: "{{kubeconfig}}"  
    state: patched
    template: "files/certmanager-console-config.yaml"
