- name: ACM - Install ACM Operator
  kubernetes.core.k8s:
    kubeconfig: "{{kubeconfig}}"
    state: present
    template: "files/acm.yaml"


- name: ACM -  Wait for the CRD MulticlusterHub to become available
  kubernetes.core.k8s_info:
    kubeconfig: "{{kubeconfig}}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: multiclusterhubs.operator.open-cluster-management.io
  register: r_crd_multiclusterhub
  retries: 200
  delay: 10
  until:
  - r_crd_multiclusterhub.resources is defined
  - r_crd_multiclusterhub.resources | list | length == 1

- name: ACM -  Create MulticlusterHub Cluster
  kubernetes.core.k8s:
    kubeconfig: "{{kubeconfig}}"
    state: present
    definition: "{{ lookup('file', 'files/acm-multiclusterhub.yaml') | from_yaml_all }}"
  retries: 20
  delay: 10


- name: Wait for MultiClusterHub to reach Running phase
  kubernetes.core.k8s_info:
    kubeconfig: "{{kubeconfig}}"  
    api_version: operator.open-cluster-management.io/v1
    kind: MultiClusterHub
    name: multiclusterhub
    namespace: open-cluster-management
  register: mch_status
  # Retries until the phase is explicitly 'Running'
  until:
    - mch_status.resources | length > 0
    - mch_status.resources[0].status.phase is defined
    - mch_status.resources[0].status.phase == "Running"
  retries: 60
  delay: 10
