{{- if .Values.enableExport }}
{{- range .Values.rbac.users }}
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: {{ . }}-application
spec:
  selector:
    kubevirt.io/domain: database
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  name: database
  namespace: {{ . }}-application
{{- end }}
{{- end }}
