wetty:
  ssh:
    autoSshToBastion: "false"

content:
  repoUrl: "https://github.com/manuvaldi/techday2026-virt.git"
  repoRef: "main"
  antoraPlaybook: "tutorial/site.yml"
  uiConfig: "tutorial/ui-config.yml"

guid: techday2026
