## Precreate certificates
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: custom-console-cert
  namespace: openshift-console
spec:
  secretName: custom-console-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: console.apps.{{ocp_cluster_name}}.{{ocp_base_domain}}
  dnsNames:
  - console.apps.{{ocp_cluster_name}}.{{ocp_base_domain}}
  - console-openshift-console.apps.{{ocp_cluster_name}}.{{ocp_base_domain}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oauth-cert
  namespace: openshift-authentication
spec:
  secretName: oauth-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: oauth.apps.{{ocp_cluster_name}}.{{ocp_base_domain}}
  dnsNames:
  - oauth.apps.{{ocp_cluster_name}}.{{ocp_base_domain}}
  - oauth-openshift.apps.{{ocp_cluster_name}}.{{ocp_base_domain}}

## Recreate secrets in accordance namespace
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: custom-console-cert
  namespace: openshift-ingress
spec:
  secretName: custom-console-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: console.apps.{{ocp_cluster_name}}.{{ocp_base_domain}}
  dnsNames:
  - console.apps.{{ocp_cluster_name}}.{{ocp_base_domain}}
  - console-openshift-console.apps.{{ocp_cluster_name}}.{{ocp_base_domain}}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oauth-cert
  namespace: openshift-config
spec:
  secretName: oauth-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: oauth.apps.{{ocp_cluster_name}}.{{ocp_base_domain}}
  dnsNames:
  - oauth.apps.{{ocp_cluster_name}}.{{ocp_base_domain}}
  - oauth-openshift.apps.{{ocp_cluster_name}}.{{ocp_base_domain}}

